#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Shellscript based wizard to setup mesh networks
LUCI_DEPENDS:=+as100meshconfig

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
